### PR TITLE
Roxygen run + utils.R updates for issue #28

### PR DESCRIPTION
**Pull request by 1beb**
RE: #28 
Looks like line endings got caught up in this (you're probably working on win / I'm on nix)

Files actually updated: 

- DESCRIPTION (Adding dplyr)
- NAMESPACE (Adding dplyr)
- Roygen updates
- R/elasticsearch.R (for importFrom)
- L404 of R/utils.R

### CODE REVIEW

**Comment by BenLinnik** [comment]
Why this is not merged yet? Thanks a lot for the fixes! 🚀

**Comment by AlexIoannides** [comment]
My apologies - this completely fell off of my radar (I started a new job around the time this was originally submitted and I have been a bit saturated since then).

Am I right in thinking that there are only two line changes in the above?

**Comment by AlexIoannides** [comment]
I have moved this to a new PR - #52 - that container only those files that need to be changed.

**Comment by 1beb** [comment]
I re ran roxygen with most recent version as no one had run it and if I
recall some pieces of docs were not in Rd format/missing. I did it with
intent. Although now I can't remember why.

**Comment by AlexIoannides** [comment]
This fix has been merged in #52 and submitted to CRAN as v0.3.1.

**Pull request closed without merging**
